# Generated by Django 6.0.5 on 2026-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/default.png', null=True, upload_to='perfiles/'),
        ),
    ]
