# Generated by Django 6.0.5 on 2026-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/dlyrpc828/image/upload/v1779727559/default_sgee5l.png', null=True, upload_to='perfiles/'),
        ),
    ]
