# Generated by Django 6.0.5 on 2026-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_corte', models.CharField(choices=[('corte_tijera', 'Corte a tijera'), ('corte_maquina', 'Corte a máquina'), ('solo_barba', 'Solo barba'), ('corte_barba', 'Corte + barba')], default='corte_maquina', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=50)),
                ('notas', models.TextField(blank=True, help_text='Indicaciones especiales (opcional)', null=True)),
                ('telefono', models.CharField(help_text='Teléfono de contacto (obligatorio)', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
