# Generated by Django 6.0.5 on 2026-05-22 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_slot',
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'confirmado'])), fields=('fecha', 'hora'), name='unique_active_slot'),
        ),
    ]
